### ISSUE TITLE
Set up github actions for automatic testing on pull requests

### ISSUE THREAD

**Issue by IdelsTak** [IdelsTak/meta-data#3]
#### Details

1. **Workflow File:** Create something like `.github/workflows/test.yml`.
2. **Trigger:** On `pull_request` events.
3. **Environment:** Latest stable Java, multiple OS (Ubuntu, MacOS, Windows) if needed.
4. **Steps**:
   - Checkout repo.
   - Set up Java.
   - Install dependencies.
   - Run tests.

#### Example Workflow

```yaml
name: Java CI

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install dependencies
      run: ./mvnw install

    - name: Run tests
      run: ./mvnw test
```

### Benefits

- Automated testing on every pull request.
- Early detection of issues.
- Improved code quality.
- Reduced manual testing.

### References:

- [GitHub Actions Documentation](https://docs.github.com/en/actions)
- [Setup Java with GitHub Actions](https://github.com/actions/setup-java)
